[mypy.*]
python_version = 3.9
check_untyped_defs = true
disallow_untyped_defs = false
warn_return_any = true
warn_unused_configs = true
explicit_package_bases = true
namespace_packages = false
mypy_path = .
ignore_missing_imports = True

[mypy-tests.*]
ignore_missing_imports = true
disallow_untyped_defs = false
ignore_errors = True

[mypy-test_*]
ignore_missing_imports = true
disallow_untyped_defs = false

[mypy-src.*]
ignore_missing_imports = false
check_untyped_defs = true

[mypy-requests.*]
ignore_missing_imports = true" > mypy.ini
